import { ThemeMode } from '../types';

export interface ThemeConfig {
  id: ThemeMode;
  name: string;
  category: 'dark' | 'light';
  description: string;
  bg: string;
  cardBg: string;
  subAlt: string;
  textColor: string;
  subColor: string;
  mainColor: string;
  errorColor: string;
  correctColor: string;
  extraColor: string;
  caretColor: string;
  glowColor?: string;
  isDark: boolean;
}

export const themes: Record<string, ThemeConfig> = {
  dark: {
    id: 'dark',
    name: 'Cyber Neo Cyan (Kiber Sian)',
    category: 'dark',
    description: 'Chuqur kosmik okean, elektr sian neon nur va ultra-tiniq yozuv',
    bg: '#060913',
    cardBg: '#0b1220',
    subAlt: '#152238',
    textColor: '#f8fafc',
    subColor: '#627899',
    mainColor: '#06b6d4',
    errorColor: '#f43f5e',
    correctColor: '#e2e8f0',
    extraColor: '#38bdf8',
    caretColor: '#00f0ff',
    glowColor: 'rgba(6, 182, 212, 0.25)',
    isDark: true,
  },
  emerald: {
    id: 'emerald',
    name: 'Nordic Emerald (Zumrad Kecha)',
    category: 'dark',
    description: 'Qutb yog\'dusi, chuqur zumrad qorong\'ulik va yashil neon kursor',
    bg: '#040d0e',
    cardBg: '#09181a',
    subAlt: '#132c2e',
    textColor: '#f0fdf4',
    subColor: '#5e8381',
    mainColor: '#10b981',
    errorColor: '#f43f5e',
    correctColor: '#ecfdf5',
    extraColor: '#34d399',
    caretColor: '#10b981',
    glowColor: 'rgba(16, 185, 129, 0.25)',
    isDark: true,
  },
  tokyo: {
    id: 'tokyo',
    name: 'Tokyo Synthwave (Tokio Neon)',
    category: 'dark',
    description: 'Tokio tungi osmoni, yorqin neon binafsha va elektr pushti nur',
    bg: '#0a0815',
    cardBg: '#131026',
    subAlt: '#221d42',
    textColor: '#f5f3ff',
    subColor: '#7c779d',
    mainColor: '#a855f7',
    errorColor: '#f43f5e',
    correctColor: '#faf5ff',
    extraColor: '#e879f9',
    caretColor: '#c084fc',
    glowColor: 'rgba(168, 85, 247, 0.25)',
    isDark: true,
  },
  sapphire: {
    id: 'sapphire',
    name: 'Royal Sapphire (Kechki Safir)',
    category: 'dark',
    description: 'Moviy kosmik dengiz, qirollik safir ko\'ki va muzdek moviy aksent',
    bg: '#070e1c',
    cardBg: '#0e1a33',
    subAlt: '#1a2d54',
    textColor: '#f8fafc',
    subColor: '#6b84ac',
    mainColor: '#38bdf8',
    errorColor: '#f43f5e',
    correctColor: '#f0f9ff',
    extraColor: '#60a5fa',
    caretColor: '#38bdf8',
    glowColor: 'rgba(56, 189, 248, 0.25)',
    isDark: true,
  },
  magma: {
    id: 'magma',
    name: 'Crimson Magma (Qizil Vulqon)',
    category: 'dark',
    description: 'Qora grafit fon, yonayotgan qizil olov va otashin geymer dizayni',
    bg: '#0e090a',
    cardBg: '#191113',
    subAlt: '#2c1c20',
    textColor: '#fff1f2',
    subColor: '#92757a',
    mainColor: '#f43f5e',
    errorColor: '#e11d48',
    correctColor: '#ffe4e6',
    extraColor: '#fb7185',
    caretColor: '#f43f5e',
    glowColor: 'rgba(244, 63, 94, 0.25)',
    isDark: true,
  },
  sunset: {
    id: 'sunset',
    name: 'Sunset Horizon (Oltin Ufq)',
    category: 'dark',
    description: 'Kechki quyosh botishi, iliq to\'q fon va yorqin qahrabo olov nuri',
    bg: '#0e0a08',
    cardBg: '#1a120e',
    subAlt: '#2e1e17',
    textColor: '#fff7ed',
    subColor: '#96796c',
    mainColor: '#f97316',
    errorColor: '#f43f5e',
    correctColor: '#ffedd5',
    extraColor: '#fb923c',
    caretColor: '#f97316',
    glowColor: 'rgba(249, 115, 22, 0.25)',
    isDark: true,
  },
  forest: {
    id: 'forest',
    name: 'Matcha Zen (Bambuk O\'rmoni)',
    category: 'dark',
    description: 'Tinchlantiruvchi chuqur tabiat, yapon bambuki va ko\'zga orom beruvchi yashillik',
    bg: '#070e0a',
    cardBg: '#0f1a12',
    subAlt: '#1b2e21',
    textColor: '#f0fdf4',
    subColor: '#688673',
    mainColor: '#22c55e',
    errorColor: '#f43f5e',
    correctColor: '#dcfce7',
    extraColor: '#4ade80',
    caretColor: '#22c55e',
    glowColor: 'rgba(34, 197, 94, 0.25)',
    isDark: true,
  },
  gold: {
    id: 'gold',
    name: 'Cyber Obsidian (Oltin Qora)',
    category: 'dark',
    description: 'Klassik qora obsidian va hashamatli oltin sariq ranglar uyg\'unligi',
    bg: '#090b11',
    cardBg: '#121622',
    subAlt: '#1c2336',
    textColor: '#f8fafc',
    subColor: '#637289',
    mainColor: '#f59e0b',
    errorColor: '#f43f5e',
    correctColor: '#f8fafc',
    extraColor: '#fb923c',
    caretColor: '#f59e0b',
    glowColor: 'rgba(245, 158, 11, 0.25)',
    isDark: true,
  },
  light: {
    id: 'light',
    name: 'Porcelain Clean (Ultra Yorug\')',
    category: 'light',
    description: 'Ultra toza oq qog\'oz, qora tiniq harflar va zamonaviy ko\'k sapfir aksent',
    bg: '#f8fafc',
    cardBg: '#ffffff',
    subAlt: '#e2e8f0',
    textColor: '#0f172a',
    subColor: '#64748b',
    mainColor: '#0284c7',
    errorColor: '#e11d48',
    correctColor: '#0f172a',
    extraColor: '#ea580c',
    caretColor: '#0284c7',
    glowColor: 'rgba(2, 132, 199, 0.15)',
    isDark: false,
  },
  sepia: {
    id: 'sepia',
    name: 'Retro Coffee (Qahva & Pergament)',
    category: 'light',
    description: 'Qadimiy issiq pergament qog\'oz, qahva espressosi va retro klassika',
    bg: '#f5ede2',
    cardBg: '#fcf6ee',
    subAlt: '#e5dac8',
    textColor: '#261e1b',
    subColor: '#7c6f66',
    mainColor: '#8c532b',
    errorColor: '#be123c',
    correctColor: '#261e1b',
    extraColor: '#c2410c',
    caretColor: '#8c532b',
    glowColor: 'rgba(140, 83, 43, 0.15)',
    isDark: false,
  },
};

export const THEME_LIST = Object.values(themes);

// Safe helper that always guarantees a valid ThemeConfig
export const getSafeThemeConfig = (themeKey?: string): ThemeConfig => {
  if (themeKey && themes[themeKey]) return themes[themeKey];
  return themes.dark;
};
