/**
 * Advanced Anti-Cheat & Code Security System for Yolnoma Typing
 *
 * Security Features:
 * - Anti Auto-Typer & Chrome Extensions: Detects untrusted events & inhuman keystroke intervals (<8ms continuous).
 * - Silent Copy/Paste/Cut Disabling: Ctrl+C, Ctrl+V, Ctrl+X, and Right-Click paste are disabled (prevented) silently WITHOUT banning the user.
 * - DevTools Inspection Disabling: F12, Ctrl+Shift+I/J/C, Ctrl+U, Ctrl+S, Right-Click menu are blocked.
 * - PrintScreen protection: Clears clipboard on PrintScreen press.
 * - Persistent Device & Account Ban for Auto-Typer Bots.
 */

import { ref, update } from 'firebase/database';
import { rtdb } from '../config/firebase';
import type { KeyboardEvent as ReactKeyboardEvent } from 'react';

class AntiCheatSystem {
  private keyTimes: number[] = [];
  private onCheatCallback: ((reason: string) => void) | null = null;
  private isListening = false;
  private currentUserId: string | null = null;

  public init(onCheat: (reason: string) => void, userId?: string | null) {
    this.onCheatCallback = onCheat;
    if (userId) this.currentUserId = userId;

    if (this.isListening) return;
    this.isListening = true;

    this.attachGlobalSecurityListeners();
  }

  public setUserId(userId: string | null) {
    this.currentUserId = userId;
  }

  public isDeviceBanned(): { banned: boolean; reason: string | null } {
    try {
      const banned = localStorage.getItem('yolnoma_device_banned') === 'true';
      const reason = localStorage.getItem('yolnoma_ban_reason');
      return { banned, reason };
    } catch {
      return { banned: false, reason: null };
    }
  }

  public clearDeviceBan() {
    try {
      localStorage.removeItem('yolnoma_device_banned');
      localStorage.removeItem('yolnoma_ban_reason');
    } catch (e) {
      console.warn('LocalStorage unban error:', e);
    }
  }

  public banDeviceAndUser(reason: string) {
    try {
      localStorage.setItem('yolnoma_device_banned', 'true');
      localStorage.setItem('yolnoma_ban_reason', reason);
    } catch (e) {
      console.warn('LocalStorage ban error:', e);
    }

    if (this.currentUserId) {
      try {
        update(ref(rtdb, `users/${this.currentUserId}`), {
          isBanned: true,
          blockReason: reason,
          bannedAt: Date.now()
        }).catch(() => {});
      } catch (err) {
        console.warn('RTDB ban user error:', err);
      }
    }

    this.triggerCheat(reason);
  }

  public resetTest() {
    this.keyTimes = [];
  }

  /**
   * Evaluates keystroke timing dynamics to detect Auto-Typer scripts/extensions
   */
  public registerKeystroke(e: ReactKeyboardEvent<HTMLInputElement> | KeyboardEvent, typedLength: number): boolean {
    const now = performance.now();

    // 1. Detect untrusted artificial events (generated by extension scripts or auto-typers)
    if (e.isTrusted === false) {
      this.banDeviceAndUser('Avto-Typer (Grom/Google Chrome) kengaytmasi yoki dasturiy harakat aniqlandi!');
      return false;
    }

    // 2. Measure delay between physical keystrokes
    if (this.keyTimes.length > 0) {
      const lastTime = this.keyTimes[this.keyTimes.length - 1];
      const delta = now - lastTime;

      // Inhumanly fast typing interval (< 8ms continuously)
      if (delta < 8) {
        this.keyTimes.push(now);
        // If more than 4 consecutive sub-8ms inputs occur -> Bot detected & BAN!
        if (this.keyTimes.length > 5) {
          const recentDeltas = [];
          for (let i = this.keyTimes.length - 5; i < this.keyTimes.length - 1; i++) {
            recentDeltas.push(this.keyTimes[i + 1] - this.keyTimes[i]);
          }
          const avgDelta = recentDeltas.reduce((a, b) => a + b, 0) / recentDeltas.length;
          if (avgDelta < 12) {
            this.banDeviceAndUser('Robotik tezlik (Auto-Typer Bot) aniqlandi va kirish bloklandi!');
            return false;
          }
        }
      }
    }

    this.keyTimes.push(now);
    if (this.keyTimes.length > 20) {
      this.keyTimes.shift();
    }

    return true;
  }

  private triggerCheat(reason: string) {
    if (this.onCheatCallback) {
      this.onCheatCallback(reason);
    }
  }

  private attachGlobalSecurityListeners() {
    // Disable Right-Click Context Menu (Silently)
    document.addEventListener('contextmenu', (e) => {
      e.preventDefault();
      return false;
    });

    // Disable Selection across entire body (Silently)
    document.addEventListener('selectstart', (e) => {
      const target = e.target as HTMLElement;
      if (target && target.tagName !== 'INPUT' && target.tagName !== 'TEXTAREA') {
        e.preventDefault();
      }
    });

    // Disable Copy, Cut, Paste globally SILENTLY without banning
    document.addEventListener('copy', (e) => {
      e.preventDefault();
    });
    document.addEventListener('cut', (e) => {
      e.preventDefault();
    });
    document.addEventListener('paste', (e) => {
      e.preventDefault();
      // SILENT PREVENTION: Stop pasting, do NOT ban!
    });

    // Global Keydown protections (F12, DevTools, View Source, PrintScreen)
    window.addEventListener('keydown', (e) => {
      const key = e.key.toLowerCase();

      // Block F12
      if (e.key === 'F12') {
        e.preventDefault();
        e.stopPropagation();
        return false;
      }

      // Block Ctrl+Shift+I, Ctrl+Shift+J, Ctrl+Shift+C (DevTools)
      if (e.ctrlKey && e.shiftKey && (key === 'i' || key === 'j' || key === 'c')) {
        e.preventDefault();
        e.stopPropagation();
        return false;
      }

      // Block Cmd+Option+I (Mac DevTools)
      if (e.metaKey && e.altKey && (key === 'i' || key === 'j' || key === 'c')) {
        e.preventDefault();
        e.stopPropagation();
        return false;
      }

      // Block Ctrl+U (View Source) and Ctrl+S
      if (e.ctrlKey && (key === 'u' || key === 's')) {
        e.preventDefault();
        e.stopPropagation();
        return false;
      }

      // Block PrintScreen (PrtScn)
      if (e.key === 'PrintScreen' || key === 'prtscr' || key === 'snapshot') {
        e.preventDefault();
        if (navigator.clipboard && navigator.clipboard.writeText) {
          navigator.clipboard.writeText('');
        }
        return false;
      }
    });

    // Clear clipboard on PrintScreen release
    window.addEventListener('keyup', (e) => {
      if (e.key === 'PrintScreen') {
        if (navigator.clipboard && navigator.clipboard.writeText) {
          navigator.clipboard.writeText('');
        }
      }
    });
  }
}

export const antiCheatManager = new AntiCheatSystem();
