/**
 * Advanced Anti-Cheat, Console Hardening & Integrity Protection System for Yolnoma Typing
 *
 * Security Features:
 * - Active DevTools Detector (Pre-entry & Runtime): Detects DevTools opened BEFORE navigating or DURING session.
 * - 100% Function Key Lock (F1-F24): Blocks all F-keys individually and in any combination (F5+F12, Ctrl+F5, Shift+F5, etc.)
 * - Capture-Phase Triple-Layer Interception: Binds to window, document, and documentElement in capture phase.
 * - DevTools & Source Protection: Blocks Ctrl+Shift+I/J/C/K/E/S, Cmd+Alt+I/J/C/K/U, Ctrl+U (view source), Ctrl+S (save), Ctrl+P (print).
 * - Console Sanitization: Neutralizes window console methods to prevent script injection and DOM inspection.
 * - Auto-Typer & Bot Detection: Millisecond keystroke dynamics and untrusted event filtering.
 * - Score Validation Engine: Validates WPM, keystroke delta, accuracy, and Dino Runner distance/scores.
 */

import { ref, update } from 'firebase/database';
import { rtdb } from '../config/firebase';
import type { KeyboardEvent as ReactKeyboardEvent } from 'react';

// Regex matching any function key from F1 to F24
const FUNCTION_KEY_REGEX = /^F([1-9]|1[0-9]|2[0-4])$/i;

type DevToolsListener = (isOpen: boolean) => void;

class AntiCheatSystem {
  private keyTimes: number[] = [];
  private onCheatCallback: ((reason: string) => void) | null = null;
  private isListening = false;
  private currentUserId: string | null = null;
  private devToolsCheckInterval: any = null;

  // DevTools detection state & listeners
  private _isDevToolsOpen = false;
  private devToolsListeners: Set<DevToolsListener> = new Set();
  private originalConsole: any = {};

  constructor() {
    // Preserve internal reference to original console before sanitizing
    if (typeof window !== 'undefined' && window.console) {
      this.originalConsole = {
        log: window.console.log,
        clear: window.console.clear,
        table: window.console.table,
        dir: window.console.dir,
      };

      this.attachGlobalSecurityListeners();
      this.sanitizeConsole();
      this.startDevToolsProtection();
    }
  }

  public init(onCheat?: (reason: string) => void, userId?: string | null) {
    if (onCheat) this.onCheatCallback = onCheat;
    if (userId) this.currentUserId = userId;

    if (!this.isListening) {
      this.isListening = true;
      this.attachGlobalSecurityListeners();
      this.sanitizeConsole();
      this.startDevToolsProtection();
    }
  }

  public setUserId(userId: string | null) {
    this.currentUserId = userId;
  }

  public isDeviceBanned(): { banned: boolean; reason: string | null } {
    try {
      const banned = localStorage.getItem('yolnoma_device_banned') === 'true';
      const reason = localStorage.getItem('yolnoma_ban_reason');
      return { banned, reason };
    } catch {
      return { banned: false, reason: null };
    }
  }

  public clearDeviceBan() {
    try {
      localStorage.removeItem('yolnoma_device_banned');
      localStorage.removeItem('yolnoma_ban_reason');
    } catch (e) {
      console.warn('LocalStorage unban error:', e);
    }
  }

  public banDeviceAndUser(reason: string) {
    try {
      localStorage.setItem('yolnoma_device_banned', 'true');
      localStorage.setItem('yolnoma_ban_reason', reason);
    } catch (e) {
      console.warn('LocalStorage ban error:', e);
    }

    if (this.currentUserId) {
      try {
        update(ref(rtdb, `users/${this.currentUserId}`), {
          isBanned: true,
          blockReason: reason,
          bannedAt: Date.now(),
        }).catch(() => {});
      } catch (err) {
        console.warn('RTDB ban user error:', err);
      }
    }

    this.triggerCheat(reason);
  }

  public resetTest() {
    this.keyTimes = [];
  }

  /**
   * Evaluates keystroke timing dynamics to detect Auto-Typer scripts/extensions
   */
  public registerKeystroke(e: ReactKeyboardEvent<HTMLInputElement> | KeyboardEvent, typedLength: number): boolean {
    const now = performance.now();

    // 1. Detect untrusted artificial events (generated by extension scripts or auto-typers)
    if (e.isTrusted === false) {
      this.banDeviceAndUser('Avto-Typer (Grom/Google Chrome) kengaytmasi yoki dasturiy harakat aniqlandi!');
      return false;
    }

    // 2. Measure delay between physical keystrokes
    if (this.keyTimes.length > 0) {
      const lastTime = this.keyTimes[this.keyTimes.length - 1];
      const delta = now - lastTime;

      // Inhumanly fast typing interval (< 8ms continuously)
      if (delta < 8) {
        this.keyTimes.push(now);
        // If more than 4 consecutive sub-8ms inputs occur -> Bot detected & BAN!
        if (this.keyTimes.length > 5) {
          const recentDeltas = [];
          for (let i = this.keyTimes.length - 5; i < this.keyTimes.length - 1; i++) {
            recentDeltas.push(this.keyTimes[i + 1] - this.keyTimes[i]);
          }
          const avgDelta = recentDeltas.reduce((a, b) => a + b, 0) / recentDeltas.length;
          if (avgDelta < 12) {
            this.banDeviceAndUser('Robotik tezlik (Auto-Typer Bot) aniqlandi va kirish bloklandi!');
            return false;
          }
        }
      }
    }

    this.keyTimes.push(now);
    if (this.keyTimes.length > 20) {
      this.keyTimes.shift();
    }

    return true;
  }

  /**
   * Validates typing score before submission to prevent console tampering
   */
  public validateTypingResult(wpm: number, accuracy: number, durationSeconds: number, charCount: number): boolean {
    if (wpm < 0 || wpm > 260) {
      return false;
    }
    if (accuracy < 0 || accuracy > 100) {
      return false;
    }
    const maxPossibleChars = durationSeconds * 25; // 25 chars/sec = 300 WPM
    if (charCount > maxPossibleChars && durationSeconds > 5) {
      return false;
    }
    return true;
  }

  /**
   * Validates Dino runner score before submission
   */
  public validateDinoScore(score: number, distance: number, obstaclesDodged: number): boolean {
    if (score < 0 || distance < 0 || obstaclesDodged < 0) return false;
    if (score > 100000) return false;
    if (distance > 0 && score > distance * 5) return false;
    return true;
  }

  private triggerCheat(reason: string) {
    if (this.onCheatCallback) {
      this.onCheatCallback(reason);
    }
  }

  /**
   * Sanitizes console output methods to protect memory and state inspection
   */
  public sanitizeConsole() {
    try {
      const emptyFunc = () => {};
      if (typeof window !== 'undefined' && (window as any).console) {
        const methods = ['log', 'debug', 'info', 'dir', 'dirxml', 'table', 'trace'];
        methods.forEach((m) => {
          try {
            (window.console as any)[m] = emptyFunc;
          } catch {}
        });
      }
    } catch {}
  }

  // ==========================================
  // ACTIVE DEVTOOLS DETECTION SYSTEM
  // ==========================================

  public isDevToolsOpen(): boolean {
    return this._isDevToolsOpen;
  }

  public subscribeDevTools(listener: DevToolsListener): () => void {
    this.devToolsListeners.add(listener);
    // Send current state immediately
    listener(this._isDevToolsOpen);
    return () => {
      this.devToolsListeners.delete(listener);
    };
  }

  private setDevToolsState(isOpen: boolean) {
    if (this._isDevToolsOpen !== isOpen) {
      this._isDevToolsOpen = isOpen;
      this.devToolsListeners.forEach((fn) => {
        try {
          fn(isOpen);
        } catch {}
      });
    }
  }

  /**
   * Checks DevTools state using multiple complementary detection vectors
   */
  public checkDevToolsNow(): boolean {
    if (typeof window === 'undefined') return false;

    let detected = false;

    // Vector 1: Window Dimensions Differential (Docked DevTools - Bottom/Right/Left)
    try {
      const widthThreshold = window.outerWidth - window.innerWidth > 160;
      const heightThreshold = window.outerHeight - window.innerHeight > 160;
      if (widthThreshold || heightThreshold) {
        detected = true;
      }
    } catch {}

    // Vector 2: Object / Element Getter Trigger (Chromium & Firefox DevTools inspects objects)
    if (!detected) {
      try {
        let getterTriggered = false;
        const probe = /./;
        probe.toString = function () {
          getterTriggered = true;
          return 'yolnoma_guard';
        };

        // If console table or dir formats the probe, getter executes
        if (this.originalConsole && this.originalConsole.dir) {
          try {
            this.originalConsole.dir(probe);
          } catch {}
        }

        if (getterTriggered) {
          detected = true;
        }
      } catch {}
    }

    // Vector 3: Debugger Timing Vector (Detached / Undocked DevTools window)
    if (!detected) {
      try {
        const start = performance.now();
        // eslint-disable-next-line no-debugger
        debugger;
        const elapsed = performance.now() - start;
        if (elapsed > 80) {
          detected = true;
        }
      } catch {}
    }

    this.setDevToolsState(detected);
    return detected;
  }

  /**
   * Background monitor for DevTools opening and closing
   */
  private startDevToolsProtection() {
    if (this.devToolsCheckInterval) return;

    // Initial check immediately
    this.checkDevToolsNow();

    // Fast polling interval (every 350ms) to immediately react when DevTools opens or closes
    this.devToolsCheckInterval = setInterval(() => {
      this.checkDevToolsNow();
    }, 350);

    // Also check on window resize
    window.addEventListener('resize', () => {
      this.checkDevToolsNow();
    });
  }

  /**
   * Checks if an event corresponds to any Function key (F1-F24) or inspect/source shortcut
   */
  private isForbiddenKeyCombo(e: KeyboardEvent): boolean {
    const key = e.key || '';
    const code = e.code || '';
    const keyCode = e.keyCode || e.which || 0;
    const lowerKey = key.toLowerCase();

    // 1. Check ALL Function keys (F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12, ... F24)
    if (
      FUNCTION_KEY_REGEX.test(key) ||
      FUNCTION_KEY_REGEX.test(code) ||
      (keyCode >= 112 && keyCode <= 135) ||
      lowerKey.startsWith('f1') ||
      lowerKey.startsWith('f2') ||
      lowerKey.startsWith('f3') ||
      lowerKey.startsWith('f4') ||
      lowerKey.startsWith('f5') ||
      lowerKey.startsWith('f6') ||
      lowerKey.startsWith('f7') ||
      lowerKey.startsWith('f8') ||
      lowerKey.startsWith('f9')
    ) {
      return true;
    }

    // 2. DevTools Shortcuts (Ctrl+Shift+I, J, C, K, E, S, P)
    if ((e.ctrlKey || e.metaKey) && e.shiftKey) {
      if (['i', 'j', 'c', 'k', 'e', 's', 'p', 'm', 'd'].includes(lowerKey)) {
        return true;
      }
    }

    // 3. Mac DevTools Shortcuts (Cmd+Option+I, J, C, K, U, S)
    if (e.metaKey && e.altKey) {
      if (['i', 'j', 'c', 'k', 'u', 's', 'p', 'e'].includes(lowerKey)) {
        return true;
      }
    }

    // 4. View Source (Ctrl+U, Cmd+U) and Save Page (Ctrl+S, Cmd+S)
    if ((e.ctrlKey || e.metaKey) && (lowerKey === 'u' || lowerKey === 's')) {
      return true;
    }

    // 5. Print Page (Ctrl+P, Cmd+P)
    if ((e.ctrlKey || e.metaKey) && lowerKey === 'p') {
      return true;
    }

    // 6. Screenshot / PrintScreen
    if (lowerKey === 'printscreen' || lowerKey === 'prtscr' || lowerKey === 'snapshot') {
      return true;
    }

    return false;
  }

  private blockEvent(e: KeyboardEvent | MouseEvent) {
    try {
      e.preventDefault();
      e.stopPropagation();
      e.stopImmediatePropagation();
      (e as any).returnValue = false;
    } catch {}
  }

  private attachGlobalSecurityListeners() {
    if (typeof window === 'undefined') return;

    // A. Disable Right-Click Context Menu (Silently across capture phase)
    const contextHandler = (e: MouseEvent) => {
      this.blockEvent(e);
      return false;
    };
    window.addEventListener('contextmenu', contextHandler, { capture: true, passive: false });
    document.addEventListener('contextmenu', contextHandler, { capture: true, passive: false });

    // B. Disable Selection across body (Silently)
    document.addEventListener(
      'selectstart',
      (e) => {
        const target = e.target as HTMLElement;
        if (target && target.tagName !== 'INPUT' && target.tagName !== 'TEXTAREA') {
          this.blockEvent(e as any);
        }
      },
      { capture: true, passive: false }
    );

    // C. Disable Copy, Cut, Paste globally SILENTLY without banning
    ['copy', 'cut', 'paste'].forEach((evt) => {
      window.addEventListener(
        evt,
        (e) => {
          const target = e.target as HTMLElement;
          if (!target || (target.tagName !== 'INPUT' && target.tagName !== 'TEXTAREA')) {
            this.blockEvent(e as any);
          }
        },
        { capture: true, passive: false }
      );
    });

    // D. Universal Key Interceptor for Keydown, Keyup, and Keypress
    const keyInterceptor = (e: KeyboardEvent) => {
      if (this.isForbiddenKeyCombo(e)) {
        this.blockEvent(e);

        // If PrintScreen is pressed, clear clipboard
        const lowerKey = (e.key || '').toLowerCase();
        if (lowerKey === 'printscreen' || lowerKey === 'prtscr' || lowerKey === 'snapshot') {
          if (navigator.clipboard && navigator.clipboard.writeText) {
            navigator.clipboard.writeText('');
          }
        }

        return false;
      }
    };

    // Attach to window, document, and documentElement in capture phase to block early
    ['keydown', 'keyup', 'keypress'].forEach((eventType) => {
      window.addEventListener(eventType, keyInterceptor as any, { capture: true, passive: false });
      document.addEventListener(eventType, keyInterceptor as any, { capture: true, passive: false });
      if (document.documentElement) {
        document.documentElement.addEventListener(eventType, keyInterceptor as any, { capture: true, passive: false });
      }
    });
  }
}

export const antiCheatManager = new AntiCheatSystem();
